version: '3.9'
services:
  ssh.cyrhades.com:
    build: ./.docker/ssh
    labels:
      ho.ctf.cyrhades: "1"
  webssh.cyrhades.com:
    build: ./.docker/webssh
    ports:
    - ${PORT}:8888
    environment:
      - HOOS_CTF_USERNAME=${HOOS_CTF_USERNAME:-}
    labels:
      ho.ctf.cyrhades: "1"
  aarchibald.cyrhades.com:
    image: anssi/fcsc2019-pwn-aarchibald:latest
    ports:
      - "4000:4000"
    labels:
      ho.ctf.cyrhades: "1"